// Code generated by github.com/goxgen/goxgen, DO NOT EDIT.

package gorm_initial

import (
    _ "embed"
    "encoding/json"
    "github.com/goxgen/goxgen/runtime/gorm_initial/generated"
)

// XgenIntrospection is the resolver for the XgenIntrospection field.
func (r *Resolver) XgenIntrospection() (*generated.XgenIntrospection, error) {
    var intr generated.XgenIntrospection
    err := json.Unmarshal(
		[]byte(`{"annotation":{"Action":[],"ListAction":[],"Resource":[]},"object":{"XgenCursorPaginationInput":{"field":[{"definition":{},"name":"first"},{"definition":{},"name":"after"},{"definition":{},"name":"last"},{"definition":{},"name":"before"}],"object":{}},"XgenPaginationInput":{"field":[{"definition":{},"name":"page"},{"definition":{},"name":"size"}],"object":{}},"XgenResourceActionType":{"field":[],"object":{}},"XgenResourceDbConfigInput":{"field":[{"definition":{},"name":"Table"}],"object":{}},"XgenResourceFieldDbConfigInput":{"field":[{"definition":{},"name":"Column"},{"definition":{},"name":"PrimaryKey"},{"definition":{},"name":"AutoIncrement"},{"definition":{},"name":"Unique"},{"definition":{},"name":"NotNull"},{"definition":{},"name":"Index"},{"definition":{},"name":"UniqueIndex"},{"definition":{},"name":"Size"},{"definition":{},"name":"Precision"},{"definition":{},"name":"Type"},{"definition":{},"name":"Scale"},{"definition":{},"name":"AutoIncrementIncrement"}],"object":{}},"XgenResourceListActionType":{"field":[],"object":{}},"XgenSort":{"field":[{"definition":{},"name":"by"},{"definition":{},"name":"direction"}],"object":{}},"XgenSortDirection":{"field":[],"object":{}},"XgenSortInput":{"field":[{"definition":{},"name":"by"},{"definition":{},"name":"direction"}],"object":{}},"XgenSortResourceConfig":{"field":[{"definition":{},"name":"Default"}],"object":{}},"XgenSortResourceConfigInput":{"field":[{"definition":{"ToObjectType":{"type":"[XgenSort!]"}},"name":"Default"}],"object":{}}},"resource":{}}`),
		&intr,
	)
    if err != nil {
        panic(err)
        return nil, err
    }
    return &intr, nil
}