// Code generated by github.com/goxgen/goxgen, DO NOT EDIT.

package gorm_initial

import (
    _ "embed"
    "encoding/json"
    "github.com/goxgen/goxgen/runtime/gorm_initial/generated"
)

//go:embed generated_xgen_introspection.json
var xgenIntrospectionJson []byte

// XgenIntrospection is the resolver for the XgenIntrospection field.
func (r *Resolver) XgenIntrospection() (*generated.XgenIntrospection, error) {
    var intr generated.XgenIntrospection
    err := json.Unmarshal(xgenIntrospectionJson, &intr)
    if err != nil {
        panic(err)
        return nil, err
    }
    return &intr, nil
}